# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editshooterwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formeditshooter(object):
    def setupUi(self, Formeditshooter):
        Formeditshooter.setObjectName("Formeditshooter")
        Formeditshooter.resize(342, 322)
        self.okButton = QtWidgets.QPushButton(Formeditshooter)
        self.okButton.setGeometry(QtCore.QRect(5, 290, 89, 25))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(Formeditshooter)
        self.cancelButton.setGeometry(QtCore.QRect(130, 290, 89, 25))
        self.cancelButton.setObjectName("cancelButton")
        self.deleteButton = QtWidgets.QPushButton(Formeditshooter)
        self.deleteButton.setGeometry(QtCore.QRect(245, 290, 89, 25))
        self.deleteButton.setObjectName("deleteButton")

        self.retranslateUi(Formeditshooter)
        QtCore.QMetaObject.connectSlotsByName(Formeditshooter)

    def retranslateUi(self, Formeditshooter):
        _translate = QtCore.QCoreApplication.translate
        Formeditshooter.setWindowTitle(_translate("Formeditshooter", "Enter/Edit shooter"))
        self.okButton.setText(_translate("Formeditshooter", "OK"))
        self.cancelButton.setText(_translate("Formeditshooter", "Cancel"))
        self.deleteButton.setText(_translate("Formeditshooter", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Formeditshooter = QtWidgets.QWidget()
    ui = Ui_Formeditshooter()
    ui.setupUi(Formeditshooter)
    Formeditshooter.show()
    sys.exit(app.exec_())
