# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewscoreswindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ViewScoresWindow(object):
    def setupUi(self, ViewScoresWindow):
        ViewScoresWindow.setObjectName("ViewScoresWindow")
        ViewScoresWindow.resize(699, 600)
        self.centralwidget = QtWidgets.QWidget(ViewScoresWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboDate = QtWidgets.QComboBox(self.centralwidget)
        self.comboDate.setGeometry(QtCore.QRect(20, 15, 196, 25))
        self.comboDate.setObjectName("comboDate")
        self.ButtShowScores = QtWidgets.QPushButton(self.centralwidget)
        self.ButtShowScores.setGeometry(QtCore.QRect(265, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtShowScores.setFont(font)
        self.ButtShowScores.setObjectName("ButtShowScores")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(25, 80, 636, 466))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tblScores = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tblScores.setObjectName("tblScores")
        self.tblScores.setColumnCount(5)
        self.tblScores.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblScores.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblScores.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblScores.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblScores.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblScores.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tblScores)
        ViewScoresWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ViewScoresWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 699, 22))
        self.menubar.setObjectName("menubar")
        ViewScoresWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ViewScoresWindow)
        self.statusbar.setObjectName("statusbar")
        ViewScoresWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ViewScoresWindow)
        QtCore.QMetaObject.connectSlotsByName(ViewScoresWindow)

    def retranslateUi(self, ViewScoresWindow):
        _translate = QtCore.QCoreApplication.translate
        ViewScoresWindow.setWindowTitle(_translate("ViewScoresWindow", "View Scores"))
        self.ButtShowScores.setText(_translate("ViewScoresWindow", "Show Scores"))
        item = self.tblScores.horizontalHeaderItem(0)
        item.setText(_translate("ViewScoresWindow", "Name"))
        item = self.tblScores.horizontalHeaderItem(1)
        item.setText(_translate("ViewScoresWindow", "EVENT"))
        item = self.tblScores.horizontalHeaderItem(2)
        item.setText(_translate("ViewScoresWindow", "DIVISION"))
        item = self.tblScores.horizontalHeaderItem(3)
        item.setText(_translate("ViewScoresWindow", "CAL"))
        item = self.tblScores.horizontalHeaderItem(4)
        item.setText(_translate("ViewScoresWindow", "SCORE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ViewScoresWindow = QtWidgets.QMainWindow()
    ui = Ui_ViewScoresWindow()
    ui.setupUi(ViewScoresWindow)
    ViewScoresWindow.show()
    sys.exit(app.exec_())
